import type { ScenarioConfig, ScenarioId } from "./types";

/** Matches `simulations/omnetpp.ini` configs (Spring 2026 NET-OPT ADVANCED v5). */
export const SCENARIOS: Record<ScenarioId, ScenarioConfig> = {
  NormalDay: {
    id: "NormalDay",
    title: "Normal Day",
    description: "Normal campus day — no registration peak",
    simTimeLimit: 180,
    useTimeProfile: false,
    stressProfile: false,
    registering: false,
    adminStudents: 15,
    csStudents: 20,
    libStudents: 10,
    arrivalWindowSec: -1,
    dataRateMbps: 5,
    apMaxClients: 50,
    apBandwidthMbps: 300,
    txPower: 20,
    regMaxSessions: 200,
    regProcessingSec: 0.02,
    monitorSamplingIntervalSec: 1,
    maxRetries: -1,
  },
  RegistrationPeak: {
    id: "RegistrationPeak",
    title: "Registration Peak",
    description: "Registration peak — CS Block bottleneck expected!",
    simTimeLimit: 600,
    useTimeProfile: true,
    stressProfile: false,
    registering: true,
    adminStudents: 30,
    csStudents: 40,
    libStudents: 20,
    arrivalWindowSec: 4,
    dataRateMbps: 20,
    apMaxClients: 3,
    apBandwidthMbps: 300,
    txPower: 20,
    regMaxSessions: 200,
    regProcessingSec: 0.075,
    monitorSamplingIntervalSec: 1,
    maxRetries: 50,
  },
  OptimizedNetwork: {
    id: "OptimizedNetwork",
    title: "Optimized Network",
    description: "Optimized — upgraded APs + server",
    simTimeLimit: 300,
    useTimeProfile: false,
    stressProfile: false,
    registering: true,
    adminStudents: 30,
    csStudents: 40,
    libStudents: 20,
    arrivalWindowSec: 4,
    dataRateMbps: 20,
    apMaxClients: 80,
    apBandwidthMbps: 600,
    txPower: 23,
    regMaxSessions: 400,
    regProcessingSec: 0.025,
    monitorSamplingIntervalSec: 1,
    maxRetries: -1,
  },
  StaggeredRegistration: {
    id: "StaggeredRegistration",
    title: "Staggered Registration",
    description: "Staggered by department — software solution, no HW upgrade",
    simTimeLimit: 300,
    useTimeProfile: true,
    stressProfile: false,
    registering: true,
    adminStudents: 30,
    csStudents: 40,
    libStudents: 20,
    arrivalWindowSec: -1,
    dataRateMbps: 20,
    apMaxClients: 8,
    apBandwidthMbps: 300,
    txPower: 20,
    regMaxSessions: 200,
    regProcessingSec: 0.05,
    monitorSamplingIntervalSec: 1,
    maxRetries: -1,
  },
  StressTest: {
    id: "StressTest",
    title: "Stress Test",
    description: "Stress test — high load with visible bottleneck",
    simTimeLimit: 300,
    useTimeProfile: true,
    stressProfile: true,
    registering: true,
    adminStudents: 40,
    csStudents: 60,
    libStudents: 20,
    arrivalWindowSec: 2,
    dataRateMbps: 20,
    apMaxClients: 4,
    apBandwidthMbps: 300,
    txPower: 20,
    regMaxSessions: 20,
    regProcessingSec: 0.2,
    monitorSamplingIntervalSec: 1,
    maxRetries: -1,
  },
};

export function scenarioIds(): ScenarioId[] {
  return Object.keys(SCENARIOS) as ScenarioId[];
}
